version: '3.8'

services:
  frontend:
    image: guinnessoverflow/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL}"
