import type { Metadata } from "next";
import "@/styles/globals.css";
import localFont from 'next/font/local'
import { Provider } from "jotai";

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} font-pretendard bg-BACKGROUND`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
